config/routes.rb
Rails.application.routes.draw do

  root to: 'categories#index'

  get 'cart' => 'checkout#show'
  post 'cart' => 'checkout#add_item'
  delete 'cart' => 'checkout#remove_item'
  get 'checkout' => 'checkout#checkout'
  post 'checkout' => 'checkout#save_checkout'

    resources :products
    resources :categories
    resources :users
    resources :addresses
    resources :payment_infos
    devise_for :users, :path_prefix => 'd'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  validates :title,:description, :image_url, :price, :inventory_quantity, :brand_id, :supplier_id, :category_id, presence: true
  validates :price, numericality: {:greater_than => 0}
  has_many :shopping_cart_items
  has_many :orders, through: :shopping_cart_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action except: [:index, :show] do
    redirect_to :root unless admin?
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

private

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price, :inventory_quantity, :brand_id, :category_id, :supplier_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2> <%= pluralize(@product.errors.count, "error") %> Prevented this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li class="errors"> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, "Enter your title" %> <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description, "Enter your description" %> <br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :image_url, "Enter the product's image link" %> <br>
    <%= f.text_field :image_url %>
  </p>
  <p>
    <%= f.label :price, "Price:" %> <br>
    <%= f.number_field :price, :step => 'any' %>
  </p>
  <p>
    <%= f.label :inventory_quantity, "Inventory Quantity:" %> <br>
    <%= f.number_field :inventory_quantity %>
  </p>
  <p>
    <%= f.label :category_id, "Select Category" %> <br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>
  <p>
    <%= f.label :brand_id, "Brand ID:" %> <br>
    <%= f.number_field :brand_id %>
  </p>
  <p>
    <%= f.label :supplier_id, "Supplier ID:" %> <br>
    <%= f.number_field :supplier_id %>
  </p>
  <p>
    <%= f.submit 'Create or Update Product', :class => "button" %>
  </p>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Destroy', product_path(@product), :class => "button",
      method: :delete%> <br>
      
<%= link_to 'Back to All Products Overview', products_path %>

app/views/products/index.html.erb
<h1> List of all Products</h1>
<div>
  <h2> <%= link_to 'Create New Product', new_product_path, :class => "crud-link" %></h2>
</div>

<div class="row">
  <%= render partial: 'shared/product_list', locals: {products: @products} %>
</div>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back to All Products Overview', products_path %>

app/views/products/show.html.erb
<div>
  <button class="test-button" value="click me">Click here</button>
</div>
<div class="row">
  <div class="product small-12 medium-4 large-4 columns">
    <%= image_tag(@product.image_url) %>
  </div>
  <div class="product small-12 medium-8 large-8 columns">

    <h1><%= @product.title %></h1><br>
    <h5><%= @product.description %></h5>
    <h3><strong><%= number_to_currency(@product.price, unit: "$", separator: ".", precision:2) %></strong></h3>
    <%= link_to 'Show Cart', cart_path, :class => "success button" %>
    <% if admin?  %>
    <%= link_to 'Edit Details', edit_product_path(@product), :class => "secondary button" %>
    <%= link_to 'Delete Product', product_path(@product), :class => "secondary button",
    method: :delete %><br>
    <% end %>

    <%= form_for :shopping_cart_item, url:'/cart' do |f| %>
    <%= hidden_field_tag 'product_id', @product.id %>
    <h5> <%= f.label :quantity, "Quantity" %>
      <%= f.select :quantity, (1..@product.inventory_quantity) %>
    </h5>
    <%= f.submit 'Add to Cart', :class => "success button" %>
    <% end %>
  </div>
</div>
<hr>
<div class="add_margin clear">
  <%= link_to '< Back to All Products', products_path,  :class => "button" %>
</div>