config/routes.rb
Rails.application.routes.draw do

  root to: 'categories#index'

  get 'cart' => 'checkout#show'
  post 'cart' => 'checkout#add_item'
  delete 'cart' => 'checkout#remove_item'
  get 'checkout' => 'checkout#checkout'
  post 'checkout' => 'checkout#save_checkout'

    resources :products
    resources :categories
    resources :users
    resources :addresses
    resources :payment_infos
    devise_for :users, :path_prefix => 'd'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :orders
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :shopping_cart_items
  belongs_to :user
  belongs_to :payment_info
  belongs_to :address


  def order_total
    sum = 0
    self.shopping_cart_items.each do |item|
      sum += item.product.price * item.quantity
    end
    sum
  end

end

app/models/payment_info.rb
class PaymentInfo < ActiveRecord::Base
  belongs_to :user
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  validates :title,:description, :image_url, :price, :inventory_quantity, :brand_id, :supplier_id, :category_id, presence: true
  validates :price, numericality: {:greater_than => 0}
  has_many :shopping_cart_items
  has_many :orders, through: :shopping_cart_items
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :addresses
  has_many :shopping_cart_items
  has_many :payment_infos
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @user = current_user
    @addresses = @user.addresses
  end

  def new
    @address = Address.new
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
    @user = current_user
    @address = Address.new(address_params)
    @user.addresses << @address
    if @address.save!
      redirect_to "/addresses"
    else
      render 'new'
    end
  end

  def show
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to @address
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to "/addresses"
  end

private

  def address_params
    params.require(:address).permit(:street_address, :street_address2, :city, :state, :zip )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :admin?
helper_method :signed_in?

private

  def admin?
    if current_user && current_user.admin?
        return true
    else
      return false
    end
  end

  def signed_in?
    if current_user
        return true
    else
      return false
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action except: [:index, :show] do
      redirect_to :root unless admin?
    end

    def index
      @categories = Category.all
      @products = Product.all
    end

    def new
      @category = Category.new
    end

    def edit
      @category = Category.find(params[:id])
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to @category
      else
        render 'new'
      end
    end

    def show
      @category = Category.find(params[:id])
      @products = Product.where(category_id: params[:id])
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        redirect_to @category
      else
        render 'edit'
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      redirect_to categories_path
    end

  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action  do
    redirect_to :root unless signed_in?
    @user = current_user
    @order = @user.orders.find_by(status: 'in_cart')
    # @order = Order.where(user_id: @user.id).first
    @shopping_cart_items = @order.shopping_cart_items
  end

  def show
    # @order = @user.orders.last
    p "{@shopping_cart_items}"
    render 'checkout/cart'
  end

  def add_item
    @order.shopping_cart_items.create(quantity: params[:shopping_cart_item][:quantity], product_id: params[:product_id])
    @shopping_cart_items = @order.shopping_cart_items
    render 'checkout/cart'
  end

  def remove_item
    item_to_delete = @shopping_cart_items.where(id: params[:id]).last
    # puts "ready to destroy: #{item_to_delete}"
    item_price_to_deduct = (item_to_delete.product.price)*(item_to_delete.quantity)
    item_to_delete.destroy
    flash[:success] = "#{item_to_delete.product.title} has been removed from cart."
    if request.xhr?
    render :nothing => true
    else
    render 'checkout/cart'
    end
    # return{amount: item_price_to_deduct}.to_json
  end

  def checkout
    # @user = current_user
    @addresses = @user.addresses
    @payment_infos = @user.payment_infos
    render 'checkout'
  end

  def save_checkout
    # @user = current_user
    # @order.update(status: 'ordered')
    # @products = @order.shopping_cart_items
    @address = @order.address if @order
    @payment_info = @order.payment_info if @order

    render 'success'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action except: [:index, :show] do
    redirect_to :root unless admin?
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

private

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price, :inventory_quantity, :brand_id, :category_id, :supplier_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action except: [:show] do
    redirect_to :root unless admin?
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    end
  end

  private

  def ensure_admin!
    unless current_user.admin?
      # sign_out current_user
      redirect_to root_path
      return false
    end
  end
  def user_params
   params.require(:user).permit(:email, :password, :admin)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper



end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_controller_helper.rb
module OrdersControllerHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_nav.html.erb
<div class="container">

  <div class="title-bar hide" data-responsive-toggle="realEstateMenu" data-hide-for="small" data-responsivetoggle="ish6kf-responsivetoggle" style="display: block;">
  <button class="menu-icon" type="button" data-toggle=""></button>
  <div class="title-bar-title">Menu</div>
  </div>

  </div>
  <div class="top-bar" id="realEstateMenu">
    <div class="top-bar-left">
      <ul class="menu accordion-menu" data-responsive-menu="accordion" role="tablist" aria-multiselectable="true" data-accordionmenu="y058x2-accordionmenu" data-responsivemenu="alhntr-responsivemenu">
        <li class="menu-text">
          <a href="/"><img src="https://s-media-cache-ak0.pinimg.com/236x/48/97/d3/4897d377aa1154f8b3e5b32cd3b25804.jpg" alt="logo" class="logo"></a>
        </li>
        <li class="menu-text"><a href="/">Shop All Products</a></li>
        <li><a href="/categories">Shop Categories</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <% if current_user %>
        <!-- <li> Welcome <%=current_user.email %></li> -->
        <li>
          <a href="/cart" class="btn btn-primary btn-success" data-toggle="modal" data-target="#shopping-cart"><i class="fi-shopping-cart"></i> Cart <span class="badge"><%= current_user.orders.find_by(status: 'in_cart').shopping_cart_items.count %></span>
          </a>
        </li>
        <li class="button small"><%= link_to "Log out", destroy_user_session_path, :method => :delete %> </li>
        <li class="button small secondary"><%= link_to "Manage Users", users_path if current_user.admin? %></li>
        <% else %>
        <li class="button small"><%= link_to "Log in", new_user_session_path %> </li>
        <li class="button small"><%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application-backup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brital.ly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="top-bar">
    <div class="container">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Brital.ly</li>
          <li class="has-submenu">
            <a href="#">Cat #1</a>
            <ul class="dropdown menu" data-submenu>
              <li><a href="/categories/1">Pants</a></li>
              <li><a href="/categories/2">Shoes</a></li>
              <li><a href="/categories/3">Shirts</a></li>
            </ul>
          </li>
          <li><a href="/categories">Categories</a></li>
          <li><a href="/products">Products</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if current_user %>
          <li> Welcome <%=current_user.email %></li>
          <%= link_to "Manage Users", users_path, :class => "button" if current_user.admin? %>
          <li><%= link_to "Log out", destroy_user_session_path, :method => :delete, :class => "button" %> </li>
          <% else %>
          <li><%= link_to "Log in", new_user_session_path, :class => "button small" %> </li>
          <li><%= link_to "Sign Up", new_user_registration_path, :class => "button small" %> </li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abezon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= stylesheet_link_tag    "application" %>
  <link href='http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render 'layouts/nav' %>
  <% if flash[:notice] %>
  <center>
    <div class="alert alert-info" data-dismiss="alert" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
  </center>
  <% end %>
  <% if flash[:error] %>
  <center>
    <div class="alert alert-danger" data-dismiss="alert" role="alert">
      <%= flash[:error] %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
  </center>
  <% end %>
  <% if flash[:success] %>
  <center>
    <div class="alert alert-success" data-dismiss="alert" role="alert">
      <%= flash[:success] %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
  </center>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/foundation/6.1.1/foundation.js'></script>

</html>

app/views/shared/_product_list.html.erb
<% @products.each do |product| %>
<div class="product small-up-2 large-up-4">
    <%= image_tag(product.image_url) %>
    <h4>
      <a href="<%=product_path(product)%>"> <%= product.title %> </a>
    </h4>
    <h5>
      Price: <%= number_to_currency(product.price, unit: "$", separator: ".", precision:2) %>
    </h5>
        <% if admin?  %>
        <h5 class="admin-only">
          <%= link_to 'Show', product_path(product), :class => "crud-link" %>
          <%= link_to 'Edit', edit_product_path(product), :class => "crud-link" %>
        </h5>
        <% end %>
</div>
<% end %>